/**
 * Authentic Indian Jain Candidate Dataset (Jain Caste & Sub-Castes)
 */
const JAIN_PROFILES = [
  {
    id: "JAIN-1001",
    name: "Dr. Prisha Mehta",
    gender: "Female",
    age: 26,
    height: 5.4,
    religion: "Jain",
    sub_caste: "Jain - Shwetambar Murti Pujak",
    gothram: "Mehta / Kashyapa",
    education: "MD, Dermatology (Gold Medalist)",
    occupation: "Consultant Dermatologist",
    company: "Lilavati Hospital & Research Centre",
    annual_income: "₹35 - 45 LPA",
    city: "Mumbai",
    state: "Maharashtra",
    mother_tongue: "Gujarati",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian (No root veggies / Chauvihar)",
    match_score: 97,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Dedicated medical professional rooted in Jain Navkar traditions and Ahimsa principles. Passionate about dermatological research, classical harmonium, and weekend spiritual satsangs. Looking for an educated, culturally grounded Jain partner with progressive family values.",
    interests: JSON.stringify(["Jain Literature", "Harmonium", "Medical Camps", "Travel", "Yoga"])
  },
  {
    id: "JAIN-1002",
    name: "Rishabh Shah",
    gender: "Male",
    age: 28,
    height: 5.11,
    religion: "Jain",
    sub_caste: "Jain - Shwetambar Murti Pujak",
    gothram: "Shah / Golechha",
    education: "B.Tech (IIT Bombay) + MBA (IIM Ahmedabad)",
    occupation: "Vice President - FinTech Strategy",
    company: "Morgan Stanley India",
    annual_income: "₹55 - 70 LPA",
    city: "Mumbai",
    state: "Maharashtra",
    mother_tongue: "Gujarati",
    marital_status: "Never Married",
    diet: "Jain Vegetarian",
    match_score: 98,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Finance professional with an entrepreneurial mindset. Family-oriented, avid badminton player, and regular practitioner of Jain Samayik and meditation. Looking for an ambitious and kind-hearted Jain life partner.",
    interests: JSON.stringify(["Fintech & Markets", "Badminton", "Vipassana", "Specialty Coffee", "Reading"])
  },
  {
    id: "JAIN-1003",
    name: "Ananya Singhi",
    gender: "Female",
    age: 25,
    height: 5.5,
    religion: "Jain",
    sub_caste: "Jain - Shwetambar Terapanthi",
    gothram: "Singhi / Surana",
    education: "Chartered Accountant (CA - All India Rank 14)",
    occupation: "Senior Manager - M&A Advisory",
    company: "Ernst & Young (EY)",
    annual_income: "₹30 - 38 LPA",
    city: "Bengaluru",
    state: "Karnataka",
    mother_tongue: "Marwari",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian",
    match_score: 94,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "CA rank holder from a respectable Terapanthi Jain family. Enthusiastic about Jain Preksha Dhyan, art curation, and exploring heritage temple architecture. Looking for a partner who values ethical living and career growth.",
    interests: JSON.stringify(["Preksha Dhyan", "Heritage Architecture", "Financial Modeling", "Classical Dance"])
  },
  {
    id: "JAIN-1004",
    name: "Siddharth Doshi",
    gender: "Male",
    age: 30,
    height: 6.0,
    religion: "Jain",
    sub_caste: "Jain - Oswal",
    gothram: "Doshi / Dugar",
    education: "MS in Artificial Intelligence, CMU",
    occupation: "Principal AI Architect",
    company: "Google Cloud",
    annual_income: "₹75 - 90 LPA",
    city: "Bengaluru",
    state: "Karnataka",
    mother_tongue: "Gujarati",
    marital_status: "Never Married",
    diet: "Jain Vegetarian",
    match_score: 95,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Tech leader working on cutting-edge generative AI models. Passionate about vegetarian gastronomy, marathons, and Jain community youth initiatives. Seeking an intellectually compatible Jain partner.",
    interests: JSON.stringify(["Artificial Intelligence", "Marathon Training", "Jain Philosophy", "Piano"])
  },
  {
    id: "JAIN-1005",
    name: "Tanvi Gandhi",
    gender: "Female",
    age: 27,
    height: 5.6,
    religion: "Jain",
    sub_caste: "Jain - Digambar",
    gothram: "Gandhi / Khandelwal",
    education: "M.Arch (Urban Design), CEPT University",
    occupation: "Lead Sustainable Architect",
    company: "Gandhi & Associates Studio",
    annual_income: "₹28 - 35 LPA",
    city: "Ahmedabad",
    state: "Gujarat",
    mother_tongue: "Gujarati",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian",
    match_score: 92,
    is_verified: true,
    is_premium: false,
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Architect passionate about green eco-habitats, Jain temple restoration, and ceramic pottery. Raised with strong Digambar Jain values, Paryushan fasting traditions, and love for nature.",
    interests: JSON.stringify(["Pottery", "Temple Restoration", "Sustainable Design", "Trekking"])
  },
  {
    id: "JAIN-1006",
    name: "Aarav Jain",
    gender: "Male",
    age: 29,
    height: 5.10,
    religion: "Jain",
    sub_caste: "Jain - Digambar",
    gothram: "Jain / Bothra",
    education: "B.Tech (NIT Trichy) + MS (Cornell University)",
    occupation: "Director - Enterprise Software",
    company: "Salesforce India",
    annual_income: "₹60 - 75 LPA",
    city: "Pune",
    state: "Maharashtra",
    mother_tongue: "Hindi",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian",
    match_score: 96,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Software director with strong ethics and traditional values. Enjoys tennis, playing the sitar, and participating in Jain community seva. Looking for a partner who believes in mutual support, respect, and shared laughter.",
    interests: JSON.stringify(["Sitar", "Tennis", "Philanthropy", "Astronomy", "Road Trips"])
  },
  {
    id: "JAIN-1007",
    name: "Yashvi Parikh",
    gender: "Female",
    age: 25,
    height: 5.3,
    religion: "Jain",
    sub_caste: "Jain - Porwal",
    gothram: "Parikh / Chhajed",
    education: "M.Sc Data Analytics, Warwick Business School (UK)",
    occupation: "Senior Data Scientist",
    company: "Amazon Web Services",
    annual_income: "₹32 - 40 LPA",
    city: "Mumbai",
    state: "Maharashtra",
    mother_tongue: "Gujarati",
    marital_status: "Never Married",
    diet: "Jain Vegetarian",
    match_score: 91,
    is_verified: true,
    is_premium: false,
    photo_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Cheerful data science enthusiast from a loving Jain family in South Mumbai. Passionate about culinary fusion, chess, and weekend nature walks. Seeking a compassionate and well-educated partner.",
    interests: JSON.stringify(["Chess", "Jain Culinary Innovation", "Biking", "Podcasts"])
  },
  {
    id: "JAIN-1008",
    name: "Bhavik Kothari",
    gender: "Male",
    age: 31,
    height: 5.9,
    religion: "Jain",
    sub_caste: "Jain - Shwetambar Sthanakwasi",
    gothram: "Kothari / Bafna",
    education: "B.Com + LLB (Corporate Law) + CA",
    occupation: "Partner - Corporate Tax & Legal",
    company: "Kothari & Chambers Law LLP",
    annual_income: "₹48 - 60 LPA",
    city: "Surat",
    state: "Gujarat",
    mother_tongue: "Gujarati",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian",
    match_score: 93,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Legal and taxation partner managing prominent Jain business groups. Active in Jain educational trusts and sports clubs. Looking for a cultured life partner with a warm heart and strong family orientation.",
    interests: JSON.stringify(["Corporate Law", "Swimming", "Community Seva", "Cricket"])
  },
  {
    id: "JAIN-1009",
    name: "Jhanvi Bhandari",
    gender: "Female",
    age: 27,
    height: 5.5,
    religion: "Jain",
    sub_caste: "Jain - Khandelwal",
    gothram: "Bhandari / Nahata",
    education: "MBA in Brand Strategy, SPJIMR Mumbai",
    occupation: "Brand Marketing Lead",
    company: "Unilever India",
    annual_income: "₹26 - 32 LPA",
    city: "Jaipur",
    state: "Rajasthan",
    mother_tongue: "Marwari",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian",
    match_score: 90,
    is_verified: true,
    is_premium: false,
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Brand strategist from a traditional Jain family in Jaipur. Loves Marwari folk art, baking Jain desserts, and participating in Mahavir Jayanti cultural programs. Looking for an educated, understanding partner.",
    interests: JSON.stringify(["Brand Design", "Marwari Art", "Baking", "Cultural Events"])
  },
  {
    id: "JAIN-1010",
    name: "Moksh Chordia",
    gender: "Male",
    age: 32,
    height: 6.1,
    religion: "Jain",
    sub_caste: "Jain - Shwetambar Terapanthi",
    gothram: "Chordia / Lodha",
    education: "B.Tech + MBA (ISB Hyderabad)",
    occupation: "Founder & CEO",
    company: "Chordia CleanTech Ventures",
    annual_income: "₹80 - 100 LPA",
    city: "Delhi NCR",
    state: "Delhi",
    mother_tongue: "Hindi",
    marital_status: "Never Married",
    diet: "Pure Jain Vegetarian",
    match_score: 97,
    is_verified: true,
    is_premium: true,
    photo_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&h=600&q=80",
    about_me: "Clean energy entrepreneur motivated by Jain principles of environmental stewardship (Aparigraha & Jiva Raksha). Keen squash player, meditator, and angel investor. Seeking a partner to share life's purposeful journey.",
    interests: JSON.stringify(["Clean Energy", "Squash", "Meditation", "Angel Investing", "Trekking"])
  }
];

module.exports = { JAIN_PROFILES };
